# Replace the "❯" symbol in the prompt with "→"
[character]      # The name of the module we are configuring is "character"
success_symbol = "→"     # The "symbol" segment is being set to "→"
error_symbol = "✗"

[aws]
symbol = " "
disabled = false

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[directory]
truncation_length = 1
use_logical_path = true
truncate_to_repo = false

[git_branch]
symbol = " "
truncation_symbol = ""

[git_status]
conflicted = "🏳${count}"
ahead = "↑"
behind = "↓"
untracked = "?${count}"
stashed = "📦${count}"
modified = "📝${count}"
staged = "S${count}"
renamed = ">>${count}"
deleted = "✗${count}"
#prefix = ""
#suffix = " "
style = "dimmed red"

[hostname]
style = "blue"
ssh_only = false
disabled = false

[kubernetes]
symbol = "⛵ "
style = "purple"
disabled = false

[terraform]
disabled = false

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
